---
title: "Stats 531 (Winter 2020) <br>'Analysis of Time Series'"
author: "Instructor: Edward L. Ionides"
output:
  html_document:
    toc: yes
csl: ecology.csl
---

------

## Course description

This course gives an introduction to time series analysis using time domain methods and frequency domain methods. 
The goal is to acquire the theoretical and computational skills required to investigate data collected as a time series. 
The first half of the course will develop classical time series methodology, including auto-regressive moving average (ARMA) models, regression with ARMA errors, and estimation of the spectral density.
The second half of the course will focus on state space model techniques for fitting structured dynamic models to time series data. 
We will progress from fitting linear, Gaussian dynamic models to fitting nonlinear models for which Monte Carlo methods are required.
Examples will be drawn from ecology, economics, epidemiology, finance and elsewhere.

A course outline, course information and grading policies are described in the [syllabus](syllabus.html).

--------------

## Class notes

1. Introduction.
[ html. ](01/notes01.html)
[ pdf. ](01/notes01.pdf)
[ R script. ](01/notes01.R)
[ annotations. ](01/notes01-annotated.pdf)

2. Time series models, trend and autocovariance.
[ pdf.  ](02/notes02.pdf)
[ R script. ](02/notes02.R)
[ annotations. ](02/notes02-annotated.pdf)

3. Stationarity, white noise, and some basic time series models.
[ pdf. ](03/notes03.pdf)
[ R script. ](03/notes03.R)
[ annotations. ](03/notes03-annotated.pdf)

4. Linear time series models and the algebra of ARMA models.
[ pdf. ](04/notes04.pdf)
[ R script. ](04/notes04.R)
[ annotations. ](04/notes04-annotated.pdf)

5. Parameter estimation and model identification for ARMA models.
[ pdf. ](05/notes05.pdf)
[ R script. ](05/notes05.R)
[ annotations. ](05/notes05-annotated.pdf)


6. Extending the ARMA model: Seasonality and trend.
[ pdf. ](06/notes06.pdf)
[ R script. ](06/notes06.R)
[ annotations. ](06/notes06-annotated.pdf)

7. Introduction to the frequency domain.
[ pdf. ](07/notes07.pdf)
[ R script. ](07/notes07.R)
[ annotations. ](07/notes07-annotated.pdf)

8. Smoothing in the time and frequency domains.
[ pdf. ](08/notes08.pdf) 
[ R script. ](08/notes08.R)
[ annotations. ](08/notes08-annotated.pdf)

9. Introduction to partially observed Markov process models.
[ pdf. ](09/notes09.pdf)
[ R script. ](09/notes09.R)
[ annotations. ](09/notes09-annotated.pdf)

10. Statistical methodology for nonlinear partially observed Markov process models.
[ pdf. ](10/notes10.pdf)
[ R script. ](10/notes10.R)
[ annotations. ](10/notes10-annotated.pdf)

11. Dynamic models and their simulation by Euler’s method.
[ pdf. ](11/notes11.pdf)
[ R script. ](11/notes11.R)
recording:
[ part 1. ](https://drive.google.com/open?id=1_R5BNaqtX0comQ_0jHNDQwAF3f8CtmmP)
[ part 2. ](https://drive.google.com/open?id=1GDce46Ucx4TKEwAhz4fClUKmpCQdZJ1k)

12. Practical likelihood-based inference for POMP models.
[ pdf. ](12/notes12.pdf)
[ R script. ](12/notes12.R)
recording:
[ part 1. ](https://drive.google.com/open?id=1yQGF6WFZzuaydikoQ4iUimwPieyuCjVW)
[ part 2. ](https://drive.google.com/open?id=1FXdDcLQFGXBj6y0gzSmZ2Cqez0OZ8PUT)
[ part 3. ](https://drive.google.com/open?id=12aq_lxdtNWbaZAdBfVRawwEkTk32Cy_O)


13. Time series models with covariates, and a case study of polio.
[ pdf. ](13/notes13.pdf)
[ R script. ](13/notes13.R)
recording:
[ part 1. ](https://drive.google.com/open?id=15lw9xbcl7jI_bA1-XnHK1jZEwS0cGEYR)
[ part 2. ](https://drive.google.com/open?id=1Wphv9RITzQGl00dvYM_zNK6iicHeN2Rw)

<!--

14. [Case study: POMP modeling to investigate financial volatility](14/notes14.html). [(R script)](notes15/notes15.R)

There are further POMP case studies, in a similar style, on [Ebola modeling](https://kingaa.github.io/sbied/ebola/ebola.html), [measles transmission](https://kingaa.github.io/sbied/measles/measles.html), and [dynamic variation in the rate of human sexual contacts](https://kingaa.github.io/sbied/contacts/contacts.html).

-->

--------

## Homework assignments

Please read the [grading policy in the syllabus](syllabus.html) before turning in homework.

* [Homework 0](hw00/hw00.html). Setting up your computational environment. Nothing to turn in.

* [Homework 1](hw01/hw01.html), due 5pm Mon Jan 20. [Solution](hw01/sol01.html).

* [Homework 2](hw02/hw02.html), due 5pm Mon Jan 27. [Solution](hw02/sol02.html).

* [Homework 3](hw03/hw03.html), due 5pm on Mon Feb 10. [Solution](hw03/sol03.html).


* [Homework 4](hw04/hw04.html), due 5pm on Mon Feb 17. [Solution](hw04/sol04.html).

* [Homework 5](hw05/hw05.html), due 5pm on Mon Mar 16. [Solution](hw05/sol05.html).

* [Homework 6](hw06/hw06.html), due 5pm on Mon Mar 23. 

<!--
[Solution](hw06/sol06.html).
-->

* [Homework 7](hw07/hw07.html), due 5pm on Mon Mar 30.

<!--
[Solution](hw07/sol07.html).
-->

* [Homework 8](hw08/hw08.html), due 5pm on Mon Apr 13.

<!--
[Solution](hw08/sol08.html).
-->


------------

## Midterm exam information

* The midterm exam is in class on Thursday February 20.

* The exam will involve reasoning about a data analysis using the theoretical and computational techniques we have studied in class. 

* The exam may include techniques covered in homeworks and will assume familiarity with the notes.
Reading the textbook is not mandatory for the exam, but may be useful to get a broader perspective.

* You should bring to the exam just pens and/or pencils. The exam will be taken without any electronic devices, books or notes.

* The best predictor of the style of the exam is the past papers from the 2016 and 2018 versions of this course:

    +  [Midterm exam for STATS 531 Winter 2016](exam/w16/mt531w16.pdf). [Solutions](exam/w16/mt531w16sol.pdf).

    +  [Midterm exam for STATS 531 Winter 2018](exam/w18/mt531w18.pdf). [Solutions](exam/w18/mt531w18sol.pdf).

    +  [Midterm exam for STATS 531 Winter 2020](exam/w20/mt531w20.pdf). [Solutions](exam/w20/mt531w20sol.pdf).



-------------------


## Midterm project

* [Information](midterm_project/midterm_project_info.html).

* [2020 midterm projects](midterm_project/index.html)

* You are welcome to browse previous [2016 midterm projects](http://ionides.github.io/531w16/midterm_project/) and  [2018 midterm projects](http://ionides.github.io/531w18/midterm_project/).



-------------

## Final project

* [Information](final_project/final_project_info.html)

* You're welcome to browse previous final projects  for [2016](http://ionides.github.io/531w16/final_project/) and  [2018](http://ionides.github.io/531w18/final_project/)


<!--

* [Projects](final_project/index.html)

-->


--------

## Using the Great Lakes cluster

Below are materials to help you get started using Great Lakes.
If you are already familiar with using R on Great Lakes, all you need to know is the class account: ```stats531w20_class```.
You are expected to use this account only for computations related to STATS 531.
Please share knowledge about cluster computing between group members, and/or on piazza, to help everyone who wants to learn these skills.

Notes on using R and pomp on Great Lakes.
[ pdf. ](cluster/STATS_531_Introduction_to_R_and_pomp_on_Great_Lakes.pdf)
[ recording. ](https://drive.google.com/open?id=1uQPghu5clYFK2lDEMhaj49yAYB8tlpc-)
<br>
Thanks to
[Charles Antonelli](http://www-personal.umich.edu/~cja/).
<br>
Charles is available by Zoom for office hours MWF 12-1 ET, for help getting started with Great Lakes.
<br>
Join Zoom Meeting https://umich.zoom.us/j/109966785.
<br>
Meeting ID: 109 966 785
<br>
Password: 066033
<br>
Cluster-related questions can also be emailed to hpc-support@umich.edu.

---------