---
title: "Final project instructions"
author: "STATS 531, Winter 2020"
output:
  html_document:
    theme: flatly
    toc: yes
---

\newcommand\prob{\mathbb{P}}
\newcommand\E{\mathbb{E}}
\newcommand\var{\mathrm{Var}}
\newcommand\cov{\mathrm{Cov}}

-----------


#### Final project outline

Find a time series dataset of your choice. Carry out a time series analysis, taking advantage of what we have learned in this course. It is expected that part of your project will involve a POMP analysis, using the modeling and inference approaches we have studied in the second half of this semester. You might like to consider the following points when planning your project.

1. A common goal of POMP analysis is to connect theory to data. This means you must think about both the theory and the data. If possible, choose a dataset on a topic for which you know, or are willing to discover, some background theory. A good way to get ideas for topics to study and places to find data is to look at the past final projects from [2016](http://ionides.github.io/531w16/final_project/index.html) and [2018](https://ionides.github.io/531w18/final_project/index.html). Each of these projects should contain the data and information about where the data came from. You may want to search for your own data set, but it is also legitimate to re-analyze data from a previous final project. If you do re-analyze data, you should explain clearly how your analysis goes beyond the previous work.

2. Computational considerations may prevent you analyzing as large a model, or as long a dataset, as you would ideally do. That is fine. Present a smaller, computationally feasible analysis and discuss possible extensions to  your analysis.

3. As for the midterm project, the time series should hopefully have at least 100 time points. You can have less, if your interests demand it. Shorter data needs additional care, since model diagnostics and asymptotic approximations become more delicate on small datasets. If your data are longer than, say, 1000 time points, you can subsample if you start having problems working with too much data. 

4. You are welcome to discuss your choice of final project with your group, and in the group instructor meetings. The projects are individual, but everyone will benefit from talking to each other about what to study and how to proceed.

To submit your project, write your report as an R markdown (Rmd) file.  Submit the report by 5pm on Wednesday April 29, as a zip file containing an Rmd file and anything else necessary to allow the grader to render the Rmd file as an html document. Projects will be posted anonymously, with source code and data, **unless you request some or all of the project to remain confidential**. After grades are assigned, you will be invited to add your name back to your project if you choose.


------------

#### Some comments on choice of data and data analysis goals

* If you already have a dataset, or scientific topic, to motivate your time series final project, that is good. Otherwise, here are some ideas.

* A standard approach for a final project is to take some previously published data, do your own time series analysis, and write it up by putting it in the context of the previously published analysis.

* You can reproduce part of a previously published analysis, being careful to explain the relationship between what you have done and what was done previously. You should also think of some things to try that are not the same as what was done previously.

* Depending on your choice of project, you may be in any of the following situations:

    1. A **pomp** representation already exists for the POMP model you want to use.

    2. Your task involves POMP models that are variations on an existing **pomp** representation.

    3. Your analysis involves a POMP model which leads you to develop your own **pomp** representation.

* If you develop a **pomp** representation of a POMP model for a new dataset, test it and demonstrate it, that is already a full project.

* The more your model derives from previous work, the further you are expected to go in carrying out a thorough data analysis.

------------

**<big>Expectations for the report</big>**. The report will be graded following the same approach used for the midterm project. It will be graded on the following categories.

* Communicating your data analysis. [10 points]

    + Raising a question. You should explain some background to the data you chose, and give motivation for the reader to appreciate the purpose of your data analysis. 

    + Reaching a conclusion. You should say what you have concluded about your question(s).

    + You will submit your source code, but you should not expect the reader to study it. If the reader has to study the source code, your report probably has not explained well enough what you were doing.

* Statistical methodology. [10 points]

    + Justify your choices for the statistical methodology.

    + The models and methods you use should be fully explained, either by references or within your report.

    + Focus on a few, carefully explained and justified, figures, tables, statistics and hypothesis tests. You may want to try many things, but only write up evidence supporting how the data help you to get from your question to your conclusions. Value the reader's time: you may lose points for including material that is of borderline relevance, or that is not adequately explained and motivated.

* Scholarship. [10 points]

    + Your report should make references where appropriate. For a well-written report the citations should be clearly linked to the material. The reader should not have to do detective work to figure out what assertion is linked to what reference.

    + You should properly acknowledge any sources (people or documents or internet sites) that contributed to your project. You are welcome, and encouraged, to look at previous projects. If you address a question related to a previous project, you must put your contribution in the context of the previous work and explain how your approach varies or extends the previous work.

    + When using a reference to point the reader to descriptions elsewhere, you should provide a brief summary in your own report to make it self-contained. 

----------

#### Methodology not covered in class

This class has focused on ARMA and POMP models, two related approaches to time domain analysis of time series. 

Time series topics on which we will spend little or no time include frequency domain analysis of multivariate time series (Shumway and Stoffer, Chapter 7) and time-frequency domain analysis using wavelets (Shumway and Stoffer, Section 4.9). 

If you decide that alternative approaches are particularly relevant for your data, you can use them in your project as a complementary approach to what we have covered in class. 

------------

#### Group meetings

You are welcome to discuss all stages of your project among your group. This is recommended; more than ever in the current situation, we should support each other and help those who hit difficulties. If you get useful feedback from your group please make an appropriate acknowledgement, just as you would for any other source.

-----------

#### Plagiarism

If material is taken directly from another source, that source must be cited and the copied material clearly attributed to the source, for example by the use of quotation marks. Failing to do this is [plagiarism](https://en.wikipedia.org/wiki/Plagiarism) and will, at a minimum, result in zero credit for the scholarship category and the section of the report in which the plagiarism occurs. Further discussion of plagiarism can be found in [On Being a Scientist: A Guide to Responsible Conduct in Research: Third edition (2009)](http://www.nap.edu/catalog.php?record_id=12192), by <i>The National Academies Press</i>.
Here is how the [Rackham Academic and Professional Integrity Policy](http://www.rackham.umich.edu/current-students/policies/academic-policies/section11#1132) describes plagiarism:

> <b> 11.2.2 Plagiarism </b>
>
> Includes:
>
>    Representing the words, ideas, or work of others as one’s own in writing or presentations, and failing to give full and proper credit to the original source.
>
>    Failing to properly acknowledge and cite language from another source, including paraphrased text.
>
>    Failing to properly cite any ideas, images, technical work, creative content, or other material taken from published or unpublished sources in any medium, including online material or oral presentations, and including the author’s own previous work.



--------

#### The COVID-19 situation

Please let me know if personal hardship is affecting your ability to study for this course. The situation is fluid at the moment. Situations may arise that call for flexibility with regard to setting and assessing coursework.


--------

 